[project]
name = "udacity-course"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain>=1.3.1",
    "langchain-openai>=1.2.2",
    "langchain-text-splitters>=1.1.0",
    "langchain-pinecone>=0.2.13",
    "langchain-tavily>=0.2.18",
    "langsmith>=0.8.5",
    "openai>=2.38.0",
    "python-dotenv>=1.2.2",
    "ruff>=0.15.14",
    "tavily>=1.1.0",
]

[dependency-groups]

[tool.black]
line-length = 88

[tool.isort]
profile = "black"
line_length = 88
